// frontend-angular/src/app/components/ui/user-management.ts
import { Component, inject, Input, OnInit, signal, OnChanges, SimpleChanges, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UserService } from '../../services/user.service';
import { CompanyService } from '../../services/company.service';

@Component({
  selector: 'app-user-management',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-6 animate-in fade-in duration-300">
      <div class="bg-white border border-slate-200 rounded-3xl shadow-sm p-8">
        
        <div class="flex items-center gap-3 mb-8">
          <div class="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center">
            <span class="material-symbols-outlined text-blue-600">person_add</span>
          </div>
          <div>
            <h2 class="text-lg font-bold text-slate-800">Invitar a un Nuevo Miembro</h2>
            <p class="text-[10px] text-slate-400 font-black uppercase tracking-widest mt-1">
              Jerarquía Real: {{ companyName() }} / {{ subName() }}
            </p>
          </div>
        </div>

        @if (status().msg) {
          <div [class]="'p-4 rounded-xl mb-6 flex items-center gap-3 font-bold text-xs uppercase tracking-widest transition-all ' + (status().type === 'success' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' : 'bg-red-50 text-red-600 border border-red-200')">
            <span class="material-symbols-outlined">{{ status().type === 'success' ? 'check_circle' : 'error' }}</span>
            <span>{{ status().msg }}</span>
          </div>
        }

        <form (submit)="saveUser()" class="space-y-8">
          
          <div class="bg-slate-50 p-6 rounded-2xl border border-slate-100 space-y-4">
            <div class="space-y-1.5">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">1. Seleccione el Perfil de Acceso *</label>
              <select required [(ngModel)]="newUser.tipo" name="tipo" class="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm font-black text-primary">
                <option value="Admin">Administrador (Control Total {{ companyName() }})</option>
                <option value="Gerente">Gerente (Encargado {{ subName() }})</option>
                <option value="Cliente">Cliente (Lectura {{ subName() }})</option>
              </select>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="space-y-1.5 opacity-80">
                <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Empresa Asignada (Real Time)</label>
                <div class="px-4 py-3 bg-white border border-slate-200 rounded-xl text-sm font-black text-slate-600 flex items-center gap-2 shadow-sm">
                  <span class="material-symbols-outlined text-blue-500 text-sm">domain</span>
                  {{ companyName() }}
                </div>
              </div>

              <div class="space-y-1.5" [class.opacity-40]="newUser.tipo === 'Admin'">
                <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">División Asignada (Real Time)</label>
                <div class="px-4 py-3 bg-white border border-slate-200 rounded-xl text-sm font-black flex items-center gap-2 shadow-sm"
                     [class.text-slate-400]="newUser.tipo === 'Admin'"
                     [class.text-primary-container]="newUser.tipo !== 'Admin'">
                  <span class="material-symbols-outlined text-sm">factory</span>
                  {{ newUser.tipo === 'Admin' ? 'Toda la Empresa' : subName() }}
                </div>
              </div>
            </div>
          </div>

          <!-- DATOS PERSONALES -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="space-y-1.5">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Nombre *</label>
              <input required [(ngModel)]="newUser.nombre" name="nombre" class="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm" placeholder="Ej. Roberto" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Apellido *</label>
              <input required [(ngModel)]="newUser.apellido" name="apellido" class="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm" placeholder="Ej. Sánchez" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">RUT del Usuario *</label>
              <input required [(ngModel)]="newUser.rut_usuario" name="rut_usuario" class="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm" placeholder="12.345.678-9" />
            </div>
            <div class="space-y-1.5">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Teléfono *</label>
              <input required [(ngModel)]="newUser.telefono" name="telefono" class="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm" placeholder="+56 9 ..." />
            </div>
            <div class="space-y-1.5 md:col-span-2">
              <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Correo Electrónico *</label>
              <input required type="email" [(ngModel)]="newUser.email" name="email" class="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-primary-container/20 outline-none transition-all text-sm font-bold" placeholder="usuario@correo.com" />
            </div>
          </div>

          <div class="pt-6 border-t border-slate-100 flex justify-end">
            <button type="submit" [disabled]="loading()" class="px-8 py-4 bg-primary-container text-white font-black rounded-xl transition-all shadow-xl shadow-blue-900/20 hover:opacity-90 active:scale-95 disabled:opacity-50 uppercase text-xs tracking-widest flex items-center gap-2">
              <span class="material-symbols-outlined text-lg">mail</span>
              {{ loading() ? 'Enviando...' : 'Invitar y Enviar Correo' }}
            </button>
          </div>
        </form>
      </div>

      <div class="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden mt-8">
        <div class="px-8 py-6 border-b border-slate-100 bg-slate-50/50 flex justify-between items-center">
          <h3 class="text-xs font-black text-primary uppercase tracking-widest">Usuarios en {{ subName() }}</h3>
          <span class="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-[10px] font-black">{{ users().length }} Usuarios</span>
        </div>
        <table class="w-full text-left text-sm">
          <thead class="bg-slate-50/50 border-b border-slate-100">
            <tr>
              <th class="px-8 py-4 font-black text-slate-400 uppercase tracking-widest text-[10px]">Nombre</th>
              <th class="px-8 py-4 font-black text-slate-400 uppercase tracking-widest text-[10px]">Email</th>
              <th class="px-8 py-4 font-black text-slate-400 uppercase tracking-widest text-[10px]">Rol</th>
              <th class="px-8 py-4 font-black text-slate-400 uppercase tracking-widest text-[10px] text-right">Acción</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-slate-100">
            @for (user of users(); track user.id) {
              <tr class="hover:bg-slate-50/30 transition-colors">
                <td class="px-8 py-4 font-bold text-slate-700">
                  {{ user.nombre }} {{ user.apellido }}
                </td>
                <td class="px-8 py-4 text-slate-500">{{ user.email }}</td>
                <td class="px-8 py-4">
                  <span class="px-3 py-1 rounded-full bg-slate-100 text-slate-600 text-[10px] font-black uppercase tracking-tight">
                    {{ user.tipo }}
                  </span>
                </td>
                <td class="px-8 py-4 text-right text-slate-300">
                  <button (click)="deleteUser(user.id)" class="hover:text-red-500 transition-all">
                    <span class="material-symbols-outlined text-lg">delete</span>
                  </button>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class UserManagementComponent implements OnInit, OnChanges {
  userService = inject(UserService);
  companyService = inject(CompanyService);
  
  @Input() subEmpresaId: string = '';
  @Input() empresaId: string = '';

  // Hacemos que los inputs también sean señales para que 'computed' reaccione a ellos
  inputEmpresaId = signal('');
  inputSubEmpresaId = signal('');

  users = this.userService.users;
  loading = signal(false);
  status = signal({ type: '', msg: '' });
  
  // NOMBRES COMPUTADOS: Reaccionan a cambios en la jerarquía Y en los inputs
  companyName = computed(() => {
    const tree = this.companyService.hierarchy();
    const id = this.inputEmpresaId();
    if (!id || tree.length === 0) return 'Buscando Empresa...';
    const emp = tree.find(e => e.id === id);
    return emp?.nombre || 'Desconocida';
  });

  subName = computed(() => {
    const tree = this.companyService.hierarchy();
    const id = this.inputSubEmpresaId();
    const parentId = this.inputEmpresaId();
    if (!id || tree.length === 0) return 'Buscando División...';
    
    // Buscar específicamente en el padre
    const emp = tree.find(e => e.id === parentId);
    const sub = emp?.subCompanies?.find((s: any) => s.id === id);
    return sub?.nombre || 'Desconocida';
  });

  newUser: any = { 
    nombre: '', apellido: '', rut_usuario: '', email: '', 
    telefono: '', cargo: '', tipo: 'Gerente', 
    empresa_id: '', sub_empresa_id: '' 
  };

  ngOnInit() {
    this.updateInputs();
    this.resetForm();
    this.loadUsers();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['subEmpresaId'] || changes['empresaId']) {
      this.updateInputs();
      this.resetForm();
      this.loadUsers();
    }
  }

  updateInputs() {
    this.inputEmpresaId.set(this.empresaId);
    this.inputSubEmpresaId.set(this.subEmpresaId);
  }

  resetForm() {
    this.newUser = { 
      nombre: '', apellido: '', rut_usuario: '', email: '', 
      telefono: '', cargo: '', tipo: 'Gerente', 
      empresa_id: this.empresaId, 
      sub_empresa_id: this.subEmpresaId 
    };
    this.status.set({ type: '', msg: '' });
  }

  loadUsers() {
    if (this.subEmpresaId) {
      this.userService.fetchUsers({ sub_empresa_id: this.subEmpresaId }).subscribe();
    }
  }

  saveUser() {
    this.loading.set(true);
    const data = {
      ...this.newUser,
      empresa_id: this.empresaId,
      sub_empresa_id: (this.newUser.tipo === 'Admin') ? '' : this.subEmpresaId,
      password: Math.random().toString(36).slice(-8)
    };

    this.userService.createUser(data).subscribe({
      next: (res: any) => {
        if (res.ok) {
          this.status.set({ type: 'success', msg: 'Invitación enviada.' });
          this.loadUsers();
          this.resetForm();
        }
        this.loading.set(false);
      },
      error: () => {
        this.status.set({ type: 'error', msg: 'Error al crear.' });
        this.loading.set(false);
      }
    });
  }

  deleteUser(id: string) {
    if (confirm('¿Eliminar?')) {
      this.userService.deleteUser(id).subscribe(() => this.loadUsers());
    }
  }
}

// frontend-app/src/pages/UserManagement.jsx
import React, { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import Sidebar from '../components/Sidebar';
import { UserPlus, Box, AlertCircle, CheckCircle, Mail } from 'lucide-react';
import axios from 'axios';

export default function UserManagement() {
  const { user } = useContext(AuthContext);
  const [empresas, setEmpresas] = useState([]);
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState({ type: '', msg: '' });

  const [formData, setFormData] = useState({
    nombre: '',
    apellido: '',
    email: '',
    telefono: '',
    cargo: '',
    tipo: 'Cliente',
    empresa_id: '',
    sub_empresa_id: ''
  });

  useEffect(() => {
    // Cargar empresas
    const fetchEmpresas = async () => {
      try {
        const token = localStorage.getItem('jwt_token');
        const res = await axios.get('/api/users/empresas', {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (res.data.ok) setEmpresas(res.data.data);
      } catch (err) {
        console.error("Error al cargar empresas", err);
      }
    };
    fetchEmpresas();
  }, []);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setStatus({ type: '', msg: '' });

    try {
      const token = localStorage.getItem('jwt_token');
      const res = await axios.post('/api/users', formData, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (res.data.ok) {
        setStatus({ type: 'success', msg: res.data.message });
        setFormData({ ...formData, nombre: '', apellido: '', email: '', telefono: '', cargo: '' });
      }
    } catch (err) {
      if (err.response && err.response.data && err.response.data.error) {
        setStatus({ type: 'error', msg: err.response.data.error });
      } else {
        setStatus({ type: 'error', msg: "Error al crear el usuario." });
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex bg-slate-50 min-h-screen font-sans">
      <Sidebar />
      <main className="flex-1 ml-64 flex flex-col">
        {/* Topbar blanca */}
        <header className="bg-white border-b border-slate-200 px-8 py-5 flex justify-between items-center sticky top-0 z-20 shadow-sm">
          <div className="flex items-center gap-4">
            <div className="p-2 bg-blue-50 rounded-lg">
              <UserPlus className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-slate-800">Gestión de Usuarios</h1>
              <p className="text-sm text-slate-500">Añada nuevos miembros y proveedores al sistema</p>
            </div>
          </div>
        </header>

        {/* Content */}
        <div className="p-8 max-w-4xl mx-auto w-full">
          <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-8">
            
            <div className="flex items-center gap-3 mb-6">
              <Mail className="text-blue-500 w-6 h-6" />
              <h2 className="text-lg font-bold text-slate-800">Invitar a un Evaluador o Cliente</h2>
            </div>
            
            <p className="text-sm text-slate-500 mb-8 border-l-4 border-blue-500 pl-4 py-1 bg-blue-50/50 rounded-r-lg">
              Al invitar a un usuario, el sistema <strong>generará y enviará automáticamente una clave inicial</strong> de 8 caracteres al correo que indiques.
            </p>

            {status.msg && (
              <div className={`p-4 rounded-xl mb-6 flex items-center gap-3 font-medium transition-all ${status.type === 'success' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' : 'bg-red-50 text-red-600 border border-red-200'}`}>
                {status.type === 'success' ? <CheckCircle className="w-5 h-5"/> : <AlertCircle className="w-5 h-5"/>}
                <span>{status.msg}</span>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Nombre */}
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Nombre *</label>
                  <input required name="nombre" value={formData.nombre} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors" placeholder="Ej. Roberto" />
                </div>

                {/* Apellido */}
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Apellido *</label>
                  <input required name="apellido" value={formData.apellido} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors" placeholder="Ej. Sánchez" />
                </div>

                {/* Email */}
                <div className="space-y-1.5 md:col-span-2">
                  <label className="text-sm font-semibold text-slate-700">Correo Electrónico * (Destino de la clave)</label>
                  <input required type="email" name="email" value={formData.email} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors" placeholder="roberto@empresa.com" />
                </div>

                {/* Rol */}
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Nivel de Acceso (Rol) *</label>
                  <select required name="tipo" value={formData.tipo} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors text-slate-800 font-medium">
                    <option value="Cliente">Cliente (Lectura)</option>
                    <option value="Gerente">Gerente (Supervisa Sub-Empresa)</option>
                    {user?.tipo === 'SuperAdmin' && <option value="Admin">Admin (Dueño Empresa Padre)</option>}
                  </select>
                </div>

                {/* Empresa */}
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Empresa Padre Asignada *</label>
                  <select required name="empresa_id" value={formData.empresa_id} onChange={(e) => setFormData({...formData, empresa_id: e.target.value, sub_empresa_id: ''})} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors text-slate-800">
                    <option value="" disabled>-- Selecciona una Empresa --</option>
                    {empresas.map(e => (
                      <option key={e.id} value={e.id}>{e.nombre} ({e.tipo_empresa})</option>
                    ))}
                  </select>
                </div>

                {/* Sub Empresa (Condicional) */}
                {(formData.tipo === 'Gerente' || (formData.tipo === 'Cliente' && formData.empresa_id)) && (
                  <div className="space-y-1.5 md:col-span-2">
                    <label className="text-sm font-semibold text-slate-700">
                      Sub Empresa / Faena {formData.tipo === 'Gerente' ? '*' : '(Opcional para Clientes)'}
                    </label>
                    <select 
                      name="sub_empresa_id" 
                      value={formData.sub_empresa_id} 
                      onChange={handleChange} 
                      className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors text-slate-800"
                      required={formData.tipo === 'Gerente'}
                    >
                      <option value="">-- {formData.tipo === 'Gerente' ? 'Debes seleccionar una sucursal' : 'Toda la Empresa Padre'} --</option>
                      {empresas.find(e => e.id === formData.empresa_id)?.sub_empresas?.map(se => (
                        <option key={se.id} value={se.id}>{se.nombre}</option>
                      ))}
                    </select>
                  </div>
                )}

                {/* Opcionales */}
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Teléfono Auxiliar</label>
                  <input name="telefono" value={formData.telefono} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors" placeholder="+56 9 ..." />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-semibold text-slate-700">Cargo</label>
                  <input name="cargo" value={formData.cargo} onChange={handleChange} className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-colors" placeholder="Ej. Supervisor de Planta" />
                </div>

              </div>

              <div className="pt-6 border-t border-slate-100 flex justify-end">
                <button type="submit" disabled={loading} className={`px-6 py-3 rounded-xl text-white font-bold transition-all shadow-md ${loading ? 'bg-blue-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700 hover:shadow-lg active:scale-95'}`}>
                  {loading ? 'Generando Contraseña...' : 'Invitar y Enviar Correo'}
                </button>
              </div>

            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
